apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    app: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        image: 427613144745.dkr.ecr.us-east-1.amazonaws.com/result:a7b5df06ba0c0c3fb195b2cd1afb4ad6bfbac8ca
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-cm


---
apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  selector:
    app: result-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: 427613144745.dkr.ecr.us-east-1.amazonaws.com/vote:a7b5df06ba0c0c3fb195b2cd1afb4ad6bfbac8ca
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-cm

---
apiVersion: v1
kind: Service
metadata:
  name: vote-app
spec:
  selector:
    app: vote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: 427613144745.dkr.ecr.us-east-1.amazonaws.com/worker:fff2ad2dd8d307fd97ca446467869e013ea8fb14
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-cm

---
apiVersion: v1
kind: Service
metadata:
  name: worker-app
spec:
  selector:
    app: worker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


--- 
apiVersion: batch/v1
kind: Job
metadata:
  name: result-app-job
spec:
  backoffLimit: 4       # Number of retries before marking as failed
  template:
    metadata:
      labels:
        app: result-app
    spec:
      restartPolicy: OnFailure
      containers:
      - name: result-app
        image: 427613144745.dkr.ecr.us-east-1.amazonaws.com/seed-data:648924fc88446ab600b5b13c95cb7e85a5485ce8
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-cm
