name: E-Voting App CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 427613144745.dkr.ecr.us-east-1.amazonaws.com

jobs:
  # Detect changes to optimize builds
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      vote-changed: ${{ steps.changes.outputs.vote }}
      result-changed: ${{ steps.changes.outputs.result }}
      worker-changed: ${{ steps.changes.outputs.worker }}
      k8s-changed: ${{ steps.changes.outputs.k8s }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            vote:
              - 'vote/**'
            result:
              - 'result/**'
            worker:
              - 'worker/**'
            k8s:
              - 'k8s/**'

  # Test Stage
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Start test environment
        run: |
          cp .env.development .env
          docker compose up -d --wait
          
      - name: Run health checks
        run: |
          sleep 10
          curl -f http://localhost:8082 || exit 1
          curl -f http://localhost:8083 || exit 1
          
      - name: Run integration tests
        run: |
          # Test vote submission
          curl -X POST -d "vote=a" http://localhost:8082
          sleep 2
          # Verify vote was processed
          docker compose logs worker | grep "Processing vote"
          
      - name: Cleanup
        if: always()
        run: docker compose down -v

  # Security Scanning
  security-scan:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.vote-changed == 'true' || needs.detect-changes.outputs.result-changed == 'true' || needs.detect-changes.outputs.worker-changed == 'true'
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  # Build Vote Service
  build-vote:
    runs-on: ubuntu-latest
    needs: [detect-changes, test]
    if: needs.detect-changes.outputs.vote-changed == 'true'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and push vote image
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          file: ./vote/Dockerfile
          target: final
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/vote:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/vote:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build Result Service  
  build-result:
    runs-on: ubuntu-latest
    needs: [detect-changes, test]
    if: needs.detect-changes.outputs.result-changed == 'true'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and push result image
        uses: docker/build-push-action@v5
        with:
          context: ./result
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/result:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/result:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build Worker Service
  build-worker:
    runs-on: ubuntu-latest
    needs: [detect-changes, test]
    if: needs.detect-changes.outputs.worker-changed == 'true'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/worker:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Update K8s Manifests (GitOps)
  update-manifests:
    runs-on: ubuntu-latest
    needs: [build-vote, build-result, build-worker]
    if: always() && (needs.build-vote.result == 'success' || needs.build-result.result == 'success' || needs.build-worker.result == 'success')
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update image tags in K8s manifests
        run: |
          # Update vote image if built
          if [[ "${{ needs.build-vote.result }}" == "success" ]]; then
            sed -i "s|${{ env.ECR_REGISTRY }}/vote:.*|${{ env.ECR_REGISTRY }}/vote:${{ github.sha }}|g" k8s/deploy-fixed.yaml
          fi
          
          # Update result image if built  
          if [[ "${{ needs.build-result.result }}" == "success" ]]; then
            sed -i "s|${{ env.ECR_REGISTRY }}/result:.*|${{ env.ECR_REGISTRY }}/result:${{ github.sha }}|g" k8s/deploy-fixed.yaml
          fi
          
          # Update worker image if built
          if [[ "${{ needs.build-worker.result }}" == "success" ]]; then
            sed -i "s|${{ env.ECR_REGISTRY }}/worker:.*|${{ env.ECR_REGISTRY }}/worker:${{ github.sha }}|g" k8s/deploy-fixed.yaml
          fi
          
      - name: Commit updated manifests
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/deploy-fixed.yaml
          git diff --staged --quiet || git commit -m "Update image tags to ${{ github.sha }}"
          git push

  # Deploy to Development
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [update-manifests]
    if: github.ref == 'refs/heads/develop'
    environment: development
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name dev-cluster --region ${{ env.AWS_REGION }}
        
      - name: Deploy to development
        run: |
          kubectl apply -f k8s/databases.yaml -n development
          kubectl apply -f k8s/deploy-fixed.yaml -n development
          kubectl rollout status deployment/vote-app -n development
          kubectl rollout status deployment/result-app -n development
          kubectl rollout status deployment/worker-app -n development

  # Deploy to Production
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [update-manifests]
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name prod-cluster --region ${{ env.AWS_REGION }}
        
      - name: Deploy to production
        run: |
          kubectl apply -f k8s/deploy-fixed.yaml -n production
          kubectl rollout status deployment/vote-app -n production
          kubectl rollout status deployment/result-app -n production
          kubectl rollout status deployment/worker-app -n production
          
      - name: Run smoke tests
        run: |
          VOTE_URL=$(kubectl get svc vote-app -n production -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          curl -f http://$VOTE_URL || exit 1