name: Build and push result image
on:
  push:
    branches:
      - main
    paths:
      - 'result/**'
      - '.github/workflows/docker-build-result.yaml'
  pull_request:
      branches:
        - main
      paths:
        - 'result/**'
        - '.github/workflows/docker-build-result.yaml'

jobs:
    build_image:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Log in to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set short SHA
            id: vars
            run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"

          - name: Build and push result image
            uses: docker/build-push-action@v2
            with:
              context: ./result
              file: ./result/Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/result-app:${{ steps.vars.outputs.short_sha }}
              cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/result-app
              cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/result-app,mode=max


    deploy_to_ec2:
        runs-on: ubuntu-latest
        needs: build_image
        steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: Set up SSH
            uses: webfactory/ssh-agent@v0.9.0
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Copy docker-compose.yml to EC2
            run: |
              scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/docker-compose.yaml