name: Build and push worker image to ecr 
on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/docker-build-worker.yaml'
  pull_request:
      branches:
        - main
      paths:
        - 'worker/**'
        - '.github/workflows/docker-build-worker.yaml'

jobs:
    build_image:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Log in to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set short SHA
            id: vars
            run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"

          - name: Build and push worker image
            uses: docker/build-push-action@v2
            with:
              context: ./worker
              file: ./worker/Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/worker-app:${{ steps.vars.outputs.short_sha }}
              cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/worker-app
              cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/worker-app,mode=max