name: Build and push vote image
on:
  push:
    branches:
      - main
    paths:
      - 'vote/**'
      - '.github/workflows/docker-build-vote.yaml'
  pull_request:
      branches:
        - main
      paths:
        - 'vote/**'
        - '.github/workflows/docker-build-vote.yaml'

jobs:
    build_image:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Log in to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build and push vote image
            uses: docker/build-push-action@v2
            with:
              context: ./vote
              file: ./vote/Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/vote-app:latest